"""empty message

Revision ID: 4d9b364b7bb5
Revises: 740bf0c2e6ba
Create Date: 2017-01-26 13:59:02.219426

"""
from alembic import op
import sqlalchemy as sa
from app.helpers import UTCDateTime
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d9b364b7bb5'
down_revision = '740bf0c2e6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('jd_file_key', sa.String(length=1024), nullable=True))
    op.drop_column('jobs', 'jd_file_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('jd_file_url', mysql.VARCHAR(length=1024), nullable=True))
    op.drop_column('jobs', 'jd_file_key')
    # ### end Alembic commands ###
