"""Set candidate.rating default 0

Revision ID: a618be76cfe3
Revises: 71381bacb795
Create Date: 2017-01-27 15:19:56.824930

"""
from alembic import op
import sqlalchemy as sa
from app.helpers import UTCDateTime
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a618be76cfe3'
down_revision = '71381bacb795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'rating',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'0'"),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'rating',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
