"""empty message

Revision ID: 740bf0c2e6ba
Revises: 0595d218001c
Create Date: 2017-01-26 13:49:57.263507

"""
from alembic import op
import sqlalchemy as sa
from app.helpers import UTCDateTime
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '740bf0c2e6ba'
down_revision = '0595d218001c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('description', mysql.MEDIUMTEXT(), nullable=True))
    op.alter_column('jobs', 'expected_salary',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'expected_salary',
               existing_type=sa.String(length=255),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=True)
    op.drop_column('jobs', 'description')
    # ### end Alembic commands ###
