"""empty message

Revision ID: 668d7f7e4831
Revises: 4d9b364b7bb5
Create Date: 2017-01-26 14:04:15.896813

"""
from alembic import op
import sqlalchemy as sa
from app.helpers import UTCDateTime
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '668d7f7e4831'
down_revision = '4d9b364b7bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('resume_key', sa.String(length=1024), nullable=True))
    op.drop_column('candidates', 'resume_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('resume_url', mysql.VARCHAR(length=1024), nullable=True))
    op.drop_column('candidates', 'resume_key')
    # ### end Alembic commands ###
