"""empty message

Revision ID: 71381bacb795
Revises: 668d7f7e4831
Create Date: 2017-01-26 17:46:05.995233

"""
from alembic import op
import sqlalchemy as sa
from app.helpers import UTCDateTime
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71381bacb795'
down_revision = '668d7f7e4831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'module_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('messages', 'secret')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('secret', mysql.VARCHAR(length=1024), nullable=False))
    op.alter_column('messages', 'module_id',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    # ### end Alembic commands ###
