"""empty message

Revision ID: 82ff64640992
Revises: a618be76cfe3
Create Date: 2017-01-27 18:31:44.902115

"""
from alembic import op
import sqlalchemy as sa
from app.helpers import UTCDateTime


# revision identifiers, used by Alembic.
revision = '82ff64640992'
down_revision = 'a618be76cfe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('position_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'position_title')
    # ### end Alembic commands ###
