"""empty message

Revision ID: 57cad9cb9070
Revises: 7844519423c0
Create Date: 2017-02-02 14:27:17.136246

"""
from alembic import op
import sqlalchemy as sa
from app.helpers import UTCDateTime
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57cad9cb9070'
down_revision = '7844519423c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('users', 'surname')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('surname', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
