"""empty message

Revision ID: 7844519423c0
Revises: ddeda6053bad
Create Date: 2017-02-01 16:08:58.074079

"""
from alembic import op
import sqlalchemy as sa
from app.helpers import UTCDateTime


# revision identifiers, used by Alembic.
revision = '7844519423c0'
down_revision = 'ddeda6053bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('published_at', UTCDateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'published_at')
    # ### end Alembic commands ###
