"""empty message

Revision ID: 43d4e336e556
Revises: 57cad9cb9070
Create Date: 2017-03-01 13:34:53.043212

"""
from alembic import op
import sqlalchemy as sa
from app.helpers import UTCDateTime


# revision identifiers, used by Alembic.
revision = '43d4e336e556'
down_revision = '57cad9cb9070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daxtra_vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('daxtra_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='daxtra_vacancy_job_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daxtra_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('daxtra_vacancy_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('daxtra_id', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name='daxtra_candidate_candidate_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['daxtra_vacancy_id'], ['daxtra_vacancies.id'], name='daxtra_candidate_daxtra_vacancy_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daxtra_candidates')
    op.drop_table('daxtra_vacancies')
    # ### end Alembic commands ###
