"""empty message

Revision ID: a8595ba2be6d
Revises: 7bfbff656adb
Create Date: 2017-03-09 13:31:36.301217

"""
from alembic import op
import sqlalchemy as sa
from app.helpers import UTCDateTime
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8595ba2be6d'
down_revision = '7bfbff656adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'jd_file_key',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'jd_file_key',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=True)
    # ### end Alembic commands ###
